<a href="https://www.kaggle.com/code/barnitkhatiwada/student-marks-prediction?scriptVersionId=251400016" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

**Importing the libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the dataset**

In [2]:
dataset = pd.read_csv('/kaggle/input/student-performance-predictions/student_performance.csv')
X = dataset.iloc[:,[3,4,5,6,7]].values
y = dataset.iloc[:, -1].values


**Label Encoding**

In [3]:
#here we dont have to encode name and gender as it does not quite affect the model.
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
# le1=LabelEncoder()
X[:,-1]=le.fit_transform(X[:,-1])
# X[:,1]=le1.fit_transform(X[:,1])
print(X)

[[85 15 78 1 0]
 [90 20 85 2 2]
 [78 10 65 0 1]
 [92 25 90 3 0]
 [88 18 82 2 2]
 [95 30 88 1 0]
 [70 8 60 0 1]
 [85 17 77 1 2]
 [82 12 70 2 1]
 [91 22 86 3 0]]


**Training the Random forest regression model on a whole dataset**

In [4]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [5]:
print(regressor.predict([['90','89','25','4','0']]))

[83.4]


**Predicting the test results**

In [6]:
y_pred = regressor.predict(X)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y.reshape(len(y),1)),1))

[[79.  80. ]
 [86.9 87. ]
 [68.6 68. ]
 [90.8 92. ]
 [83.8 85. ]
 [90.1 90. ]
 [67.4 62. ]
 [77.6 78. ]
 [72.2 72. ]
 [88.8 88. ]]


**Evaluating the code performance**

In [7]:
from sklearn.metrics import r2_score
print("Accuracy:",r2_score(y, y_pred)*100,"%")

Accuracy: 96.26634699215344 %
